name: ghidra-jython-kernel test
on: [push, pull_request]

jobs:
  test:
    name: install kernel and test REPL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: install
        run: |
          python -m pip install --upgrade pip
          python setup.py install
      
      - if: success() # if install was success, process TEST
        uses: actions/setup-java@v1 # use Java 11
        with:
          java-version: '11.0.x'
          java-package: jdk
          architecture: x64

      - name: run test
        run: |
          apt-get update && apt-get install -y unzip
          curl https://ghidra-sre.org/$(curl -s https://ghidra-sre.org/ | grep -m1 -o "ghidra_.*.zip") -o /tmp/ghidra.zip
          unzip /tmp/ghidra.zip -d /tmp/ghidra
          export GHIDRA_INSTALL_DIR=/tmp/ghidra
          pytest -v tests
